<div class="row">
	<div class="col-sm">
		<h1>Stamps</h1>
	</div>
</div>
<div class="row">
	<?php foreach($stamps as $stamp) { ?>
		<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
			<div class="card">
				<img src="/images/<?= $stamp->picture ?>" alt="">
				<p><?= $stamp->name ?> (<?= $stamp->quantity ?>)</p>
				
				<a href="/stamps/delete?id=<?= $stamp->id ?>">Delete</a>
				<a href="/stamps/update?id=<?= $stamp->id ?>">Update</a>
				<div class="box">
				<input type="checkbox" name="glued" value="glued">Glue<br>
				</div>
			</div>
		</div>
	<?php } ?>
</div>