<h1>New Stamp</h1>
<form action="/stamps/submit" method="post" enctype="multipart/form-data">
	<p>Name</p>
	<input type="text" name="name">

	<p>Year</p>
	<input type="text" name="year">

	<p>Collection</p>
	<input type="text" name="collection">

	<p>Size</p>
	<input type="text" name="size">

	<p>Quantity</p>
	<input type="text" name="quantity">

	<p>Picture</p>
	<input type="file" name="picture">

	<p>Description</p>
	<input type="text" name="description">

	<p>Glue to Album</p>
	<input type="checkbox" name="glue">

	<br><br>
	<button type="submit">Submit</button>
</form>