<div class="row">
	<div class="col-sm">
		<h1>Login</h1>
		<form action="?p=login_submit" method="post">
			<div class="form-group">
				<label for="user">Username</label>
				<input type="text" class="form-control" id="user" name="user"/>
			</div>
			<div class="form-group">
				<label for="pass">Password</label>
				<input type="password" class="form-control" id="pass" name="pass" placeholder="Password">
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
</div>